/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LogoMark: typeof import('./components/LogoMark.vue')['default']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensitiveInput: typeof import('./components/SensitiveInput.vue')['default']
  }
}

// For TSX support
declare global {
  const LogoMark: typeof import('./components/LogoMark.vue')['default']
  const NTag: typeof import('naive-ui')['NTag']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SensitiveInput: typeof import('./components/SensitiveInput.vue')['default']
}